#pragma once


#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_SPK_GPIO_BCLK  GPIO_NUM_0
#define AUDIO_I2S_SPK_GPIO_LRCK  GPIO_NUM_18
#define AUDIO_I2S_SPK_GPIO_DOUT  GPIO_NUM_17
#define AUDIO_I2S_MIC_GPIO_SCK   GPIO_NUM_11
#define AUDIO_I2S_MIC_GPIO_WS    GPIO_NUM_12
#define AUDIO_I2S_MIC_GPIO_DIN   GPIO_NUM_13 